### ISSUE TITLE
doesn't import urls

### ISSUE THREAD

**Issue by frostworx** [Bronkoknorb/a1tv-helpers#1]
hi!
first of all thank you for your work on this promising project!
looks like all other attempts are years old and broken.
I have issues to import the channels in my testsetup though.
running gentoo ~amd64 with
tvheadend-4.0.5 (completely clear settings initially) built with xmltv support
tried with ruby20 and ruby22.
the problem is the "@" in the rtp url which rejects to insert the iptv_url into the configs.
without the iptv_url tvheadend apparently fails :}
for testing I hardcoded rtp url without the "@" into RestClient.post,
which worked (the filling did, not the muxer in tvheadend).
Probably the "@" needs to be escaped somehow, but I have no clue how to do this in ruby.
Would be nice if you had any hints or fixes.

**Comment by frostworx** [comment]
me again. just installed tvheadend current master and with that version the import seems to work.
It is just scanning and all finished ones "FAILED", but maybe the service is just down atm.
sorry for the noise, probably my ticket is invalid.

**Comment by frostworx** [comment]
heh, very likely they simply block german ips eh?

**Comment by Bronkoknorb** [comment]
Hi!
Thanks for your feedback.
About the problem with the @ in the URL: Could be because I only tested it with Ruby 1.9 - maybe a problem with Ruby 2. That upgrading Tvheadend to a master version solved the problem for you is weird, as I use version 4.0.5 successfully.

About A1 TV: Of course it only works if you pay for it. See http://a1.net/tv/

Hermann

**Comment by frostworx** [comment]
hey! I hope I don't reopen the issue with answering :}
sorry, I didn't know that this is paytv, until today I never tried iptv, so I don't know anything about it.
maybe the issue wasn't in tvheadend-4.0.5 but in the way it was compiled here. I used a different ebuild (gentoo package management "build system") for the git master version.
have much fun with your project and thank you for the quick reply!
friendly,
frostwork

**Comment by dekarl** [comment]
@frostworx the 239.0.0.0/8 range is assigned by RFC 2365 for private use within an organization. (quote from Wikipedia) This means that you can only receive the IPTV channels from your own ISP. This is a common setup and independent of the pay/free status of the service.

**Comment by frostworx** [comment]
ah ic, thanks for the info! I might just stick with my good old dvbs2 vdr setup and live without iptv :}
