### ISSUE TITLE
RPI3/Osmc build issues

### ISSUE THREAD

**Issue by IgorUserowsky** [Bronkoknorb/a1tv-helpers#3]
Great set of scripts!

I am hoping to incorporate this into my Rpi3 Osmc setup, mainly to be able to easily use EPG (usually a PITA).

Two issues with installing/running:

Firstly, Osmc seems to be missing make and build-essentials, I can see how those did not make your dependencies list, but you might want to add a remark for future users.
If gem install fails with *"ERROR: Failed to build gem native extension."* - one possible solution to install rest-client is `sudo apt-get install make build-essentials`

Additionally, the A1tv .m3u has several instances of Umlauts in the channel names, which causes the tvheadend_import.rb to fail with *invalid byte sequence in US-ASCII (ArgumentError)* 
I had to go back into tvh gui and remove all entries, then replace all instances of Umlauts in the .m3u and run again. Maybe a workaround could be to change the char set in tvh?

Unfortunately, all muxes that were successfully imported eventually, fail at scan. My guess is that tvh might be somehow misconfigured. The .m3u works in IPTV Simple client, so the streams are definitively correct.

I'll try to get it fixed by diving deeper into tvh, any pointers would be appreciated.

**Comment by IgorUserowsky** [comment]
I had to close the VPN manager in Kodi for the scan to work.

**Comment by Bronkoknorb** [comment]
Thanks @IgorUserowsky. I have updated the README with the installation of make and build-essentials.
The problems with the Umlauts I did not get so far - I'll see if I get it the next time I use the scripts.
